# Ativa o perfil de desenvolvimento, fazendo o Spring carregar o application-dev.properties
spring.profiles.active=dev

spring.application.name=api

# Configurações não-secretas do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/caracameusonho_db
spring.datasource.username=admin

# Configurações do JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.frontend.url=http://localhost:5173
#app.frontend.url=https://ac4535ef1f73.ngrok-free.app
