# caraca-meu-sonho/docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: caraca-meu-sonho-db
    environment:
      POSTGRES_USER: cmsuser
      POSTGRES_PASSWORD: cmspassword
      POSTGRES_DB: cmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
