services:
  # Serviço do Banco de Dados PostgreSQL
  - type: pserv # 'pserv' é para private service, mas vamos usar 'db' para banco de dados
    name: cmsdb-prod
    runtime: postgres
    plan: free
    postgres:
      version: "16"

  # Serviço da API Spring Boot
  - type: web
    name: caraca-meu-sonho-api
    runtime: docker # DIZ AO RENDER PARA USAR O SEU DOCKERFILE
    repo: https://github.com/omarlonRosa/caraca-meu-sonho # O seu repo
    region: oregon # ou a região que preferir
    plan: free
    healthCheckPath: /
    dockerfilePath: ./backend/api/Dockerfile # Caminho correto para o Dockerfile
    dockerContext: ./backend/api # Define o contexto do build
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - fromDatabase:
          name: cmsdb-prod # O nome do serviço de banco de dados definido acima
          # Mapeia as propriedades do banco de dados para as variáveis que a nossa app espera
          propertyMappings:
            - property: host
              key: DB_HOST
            - property: port
              key: DB_PORT
            - property: database
              key: DB_NAME
            - property: user
              key: DB_USER
            - property: password
              key: DB_PASSWORD
